' Developer Express Code Central Example:
' How to: Use FunctionBindingBehavior
' 
' This example demonstrates how to use the FunctionBindingBehavior.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=T197048
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace FunctionBindingExample.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As FunctionBindingExample.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New FunctionBindingExample.Properties.Settings())), FunctionBindingExample.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return FunctionBindingExample.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
